# -*- coding: utf-8 -*-
"""Mini project Food ordering system .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOxRI9O52QDrZtmg0tVpTqFk_CsMihzT
"""

#order menu
menu = {
    'pani puri':30,
    'dahi puri':50,
    'masala puri':50,
    'sev puri':50,
    'bhel puri':50,
    'samosa chaat':70,
    'samosa ragda':70,
    'chinese bhel':80,
    'pav bhaji':70,
    'mushroom pav bhaji':70,
    'paneer pav bhaji':70,
    'cheese pav bhaji':80,
    'extra pav':15,
    'veg sandwich':50,
    'veg grilled sandwich':60,
    'cheese sandwich':50,
}

#greet
print("Welcome to Food chat")
print("pani puri: Rs30\nDahi puri: Rs50\nmasala puri: Rs50\nsev puri: Rs50\nBhel puri: Rs50\nSamosa chaat: Rs70\nSamosa ragda: Rs70\nChinese bhel: Rs80\nPav bhaji: Rs70\nMushroom pav bhaji: Rs70\nPaneer pav bhaji: Rs70\nCheese pav bhaji: Rs80\nExtra pav: Rs15\nVeg Sandwich: Rs50\nVeg grilled sandwich: Rs60\nCheese sandwich: Rs50")

order_total = 0

item_1 = input("Enter the Name of item that you want to order = ").lower()
if item_1 in menu:
  order_total += menu[item_1]
  print(f"your item {item_1} has been added to your order")
else:
  print(f"please order something that we can serve you")

Another_order = input(f"Do you want to add another item? (Yes/No)").lower()
if Another_order == "yes":
  item_2 = input("Enter the Name of second item =").lower()
  if item_2 in menu:
    order_total += menu[item_2]
    print(f"your item {item_2} has been added to your order")
  else:
    print(f"order item {item_2} is not available")

print(f"the total amount of item is to pay {order_total}")